FROM ubuntu:18.04


MAINTAINER MarlinSearch <searchmarlin@gmail.com>

RUN apt-get update && apt-get -y install autoconf libtool git ssh tar gzip ca-certificates && apt-get -y install cmake build-essential gcc zlib1g-dev libssl-dev python python-requests psmisc curl && rm -rf /var/lib/apt/lists/*
